#
# Copyright (c) 2020-2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE_IMAGE=openvino/model_server-build
FROM $BASE_IMAGE as base_build

LABEL version="1.0.0"

SHELL ["/bin/bash", "-c"]
RUN apt update && apt install -y \
        libglib2.0-dev \
        libjson-c-dev && \
        apt clean

# Setting OVMS path to reference the interface header
ENV OVMS_DIR=/ovms/src

ARG use_sgx=0

# Copy OVSA src 
WORKDIR /ovsa
COPY  Ovsa_runtime/ /ovsa/Ovsa_runtime/
COPY  Ovsa_tool/ /ovsa/Ovsa_tool

RUN mkdir -vp /ovsa-runtime/lib
RUN mkdir -vp /ovsa-runtime/usr
RUN mkdir -vp /ovsa-runtime/etc

# Build OVSA Runtime
RUN if [ "$use_sgx" == "1" ]; then \
        export GRAMINE_DIR=/ovsa/Ovsa_runtime/src/gramine && \
        cd /ovsa/Ovsa_runtime/src/ovms && \
        SGX=1 make clean all; \
    else \
        cd /ovsa/Ovsa_runtime/src/ovms && \
        make clean all; \
    fi
RUN cp /ovsa/Ovsa_runtime/src/ovms/libovsaruntime.so /ovsa/Ovsa_runtime/lib/
RUN cp -rv /ovsa/Ovsa_runtime/lib/* /ovsa-runtime/lib/

WORKDIR /
RUN tar cvzf ovsa-runtime.tar.gz /ovsa-runtime
