#
# Copyright (c) 2020-2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM openvino/model_server:latest-nginx-mtls as base_build

LABEL version="1.0.0"

ARG DL_DIR=/tmp
ARG build_type=dbg

ARG release_dir=release_files


USER root

RUN apt update && apt install -y \
        sudo \
        dbus \
        libglib2.0-0 \
        curl && \
        apt clean

WORKDIR /
RUN mkdir -vp /ovsa-runtime/lib

# Copy OVSA Runtime Library
COPY $release_dir/ovsa-runtime/lib /ovsa-runtime/lib
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:ovms/lib:/usr/lib/:/ovsa-runtime/lib/:/usr/lib/x86_64-linux-gnu

# Copy ovms_wrapper
COPY /Example/runtime/ovsa_sgx_ovms_wrapper /ovms_wrapper

# Copy nginx configurations
RUN cp /model_server.conf.template /etc/nginx/conf.d/model_server.conf 

RUN sed -i 's/worker_processes auto/worker_processes 4/g' /etc/nginx/nginx.conf
#RUN sed -i 's/80/8888/g' /etc/nginx/nginx.conf

# Create OVSA user
RUN useradd -ms /bin/bash ovsa
RUN chown -R ovsa:ovsa /ovsa-runtime

USER ovsa
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/:/ovsa-runtime/lib/:/usr/lib/x86_64-linux-gnu

USER root

ENTRYPOINT ["/bin/bash"]
CMD ["/ovms_wrapper"]
