#
# Copyright (c) 2020-2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM openvino/model_server-nginx-mtls as base_build

LABEL version="1.0.0"

ARG DL_DIR=/tmp
ARG build_type=dbg

USER root

RUN yum install -y \
        sudo && \
        yum clean all


WORKDIR /
RUN mkdir -vp /ovsa-runtime/lib

COPY /release_files/ovsa-runtime/lib /ovsa-runtime/lib
COPY /release_files/ovsa-runtime/usr/bin /usr/bin
COPY /release_files/ovsa-runtime/usr/etc /usr/etc
COPY /release_files/ovsa-runtime/usr/include /usr/include
COPY /release_files/ovsa-runtime/usr/lib /usr/lib
COPY /release_files/ovsa-runtime/usr/sbin /usr/sbin
COPY /release_files/ovsa-runtime/usr/share /usr/share
COPY /release_files/ovsa-runtime/usr/var /usr
COPY /release_files/ovsa-runtime/tpm2-abrmd/tpm2-abrmd.conf /etc/dbus-1/system.d/tpm2-abrmd.conf
COPY Scripts/guest/OVSA_tpm2_init.sh /usr/local/bin/OVSA_tpm2_init.sh

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/:/ovsa-runtime/lib/

RUN sed -i 's/"tss"/"ovsa"/g' /etc/dbus-1/system.d/tpm2-abrmd.conf
RUN sed -i 's/#set -x/set -x/g' /ovms_wrapper

RUN useradd -ms /bin/bash ovsa
RUN groupadd tss
RUN mkdir -p /var/lib/tpm
RUN useradd -M -d /var/lib/tpm -s /bin/bash -g tss tss
RUN usermod -a -G tss ovsa
RUN chown -R ovsa:ovsa /ovsa-runtime
RUN chown -R ovsa:ovsa /ovms_wrapper
RUN mkdir -p /var/run/dbus
RUN chown ovsa:ovsa /var/run/dbus
RUN chmod +x /usr/local/bin/OVSA_tpm2_init.sh

USER ovsa
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/:/ovsa-runtime/lib/
USER root

ENTRYPOINT ["/usr/bin/dumb-init", "--", "./usr/local/bin/OVSA_tpm2_init.sh"]
#ENTRYPOINT []
