#!/bin/bash
#
# Copyright (c) 2020-2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


show_usage (){
    echo "Usage: $0 <Customer License> <Controlled Access Model> <Artefacts Path>"
    return 0
}

if [ "$1" = "-h" ] || [ "$1" = "" ]
then
            show_usage
            exit 1
fi

cd $OVSA_DEV_ARTEFACTS
#echo "Customer License: $1"
CUSTOMER_LIC=$(echo $1 | cut -d '.' -f 1)
#echo "Customer Lic: $CUSTOMER_LIC"

# Delete thie files remotely before sending it
sudo -u intel ssh intel@192.168.122.79 rm -rf $3/$CUSTOMER_LIC.lic
sudo -u intel ssh intel@192.168.122.79 rm -rf $3/$CUSTOMER_LIC.dat

sudo -u intel scp -q $1 intel@192.168.122.79:$3/$CUSTOMER_LIC.lic
sudo -u intel scp -q $2 intel@192.168.122.79:$3

echo "Sent Controlled Access Model $3/$CUSTOMER_LIC.dat"
echo "Sent License $3/$CUSTOMER_LIC.c_lic"

#rm -rf /var/OVSA/artefacts/*


